# Generated by Django 2.1 on 2020-10-26 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0003_auto_20201026_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'verbose_name_plural': 'Академічні групи'},
        ),
        migrations.RenameField(
            model_name='membergroup',
            old_name='member',
            new_name='member_group',
        ),
        migrations.AddField(
            model_name='membergroup',
            name='member_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Учасник'),
        ),
    ]
