# Generated by Django 2.1 on 2020-10-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0004_auto_20201026_1910'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membergroup',
            unique_together={('member_group', 'member_user')},
        ),
    ]
