# Generated by Django 2.1 on 2020-10-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0006_auto_20201026_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
