# Generated by Django 2.1 on 2020-10-29 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0009_auto_20201028_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractModel',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nubip.Event')),
            ],
            options={
                'verbose_name_plural': 'Abstract',
            },
            bases=('nubip.event',),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Назва предмету'),
        ),
    ]
