# Generated by Django 2.1 on 2020-10-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0010_auto_20201029_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractmodel',
            options={'verbose_name_plural': 'Як Список'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('headman', 'Староста'), ('curator', 'Куратор'), ('teacher', 'Викладач'), ('head_assistant', 'Заступник директора'), ('head', 'Директор'), ('admin', 'Admin')], max_length=20, verbose_name='role'),
        ),
    ]
