# Generated by Django 2.1 on 2020-11-15 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0012_auto_20201115_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicgroup',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='academic_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nubip.AcademicGroup', verbose_name='Академічна група'),
        ),
    ]
