# Generated by Django 2.1 on 2020-11-15 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0013_auto_20201115_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
