# Generated by Django 2.1 on 2020-11-15 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0016_auto_20201115_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, verbose_name='date_of_birth'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='passport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_info', to='nubip.Passport'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_info', to='nubip.PhoneNumber'),
        ),
    ]
