# Generated by Django 2.1 on 2020-11-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0017_auto_20201115_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='add_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='uuid',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='additional_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='customer_last_name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='presence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reason',
            field=models.CharField(blank=True, choices=[('sickness', 'Хворіє'), ('important', 'Поважна'), ('home', 'Home'), ('other', 'Other')], default=None, max_length=30, null=True, verbose_name='reason'),
        ),
    ]
