# Generated by Django 2.1 on 2020-11-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0019_auto_20201115_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicgroup',
            name='member',
        ),
    ]
