# Generated by Django 2.1 on 2020-11-21 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0020_remove_academicgroup_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='academic_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nubip.AcademicGroup', verbose_name='Група'),
        ),
    ]
