# Generated by Django 2.1 on 2020-11-21 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0023_auto_20201121_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nubip.Event', verbose_name='Учасник')),
            ],
            options={
                'verbose_name_plural': 'Заняття користувача',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='events',
        ),
        migrations.AlterField(
            model_name='membergroup',
            name='member_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nubip.AcademicGroup', verbose_name='Група Учасника'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nubip.UserProfile', verbose_name='Учасник'),
        ),
        migrations.AlterUniqueTogether(
            name='userevent',
            unique_together={('event', 'user')},
        ),
    ]
