# Generated by Django 2.1 on 2020-11-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0024_auto_20201121_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='presence',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='reason',
        ),
        migrations.AddField(
            model_name='membergroup',
            name='additional_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='info'),
        ),
        migrations.AddField(
            model_name='membergroup',
            name='presence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membergroup',
            name='reason',
            field=models.CharField(blank=True, choices=[('sickness', 'Хворіє'), ('important', 'Поважна'), ('home', 'Home'), ('other', 'Other')], default=None, max_length=30, null=True, verbose_name='reason'),
        ),
    ]
