# Generated by Django 2.1 on 2020-11-21 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0026_auto_20201121_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUserEvent',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('report_presence', models.BooleanField(default=False)),
                ('report_reason', models.CharField(blank=True, choices=[('sickness', 'Хворіє'), ('important', 'Поважна'), ('home', 'Home'), ('other', 'Other')], default=None, max_length=30, null=True, verbose_name='report_reason')),
                ('report_additional_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='report_info')),
                ('report_creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_creator', to='nubip.UserProfile', verbose_name='Власник')),
                ('report_event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_event', to='nubip.Event')),
                ('report_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_user', to='nubip.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'Заняття користувача',
            },
        ),
        migrations.AlterUniqueTogether(
            name='reportuserevent',
            unique_together={('report_event', 'report_user', 'report_creator')},
        ),
    ]
