# Generated by Django 2.1 on 2020-11-21 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0027_auto_20201121_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractmodel',
            options={'verbose_name_plural': 'Звіт'},
        ),
        migrations.AlterModelOptions(
            name='reportuserevent',
            options={'verbose_name_plural': 'Звіти'},
        ),
        migrations.AlterField(
            model_name='reportuserevent',
            name='report_creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportuserevent',
            name='report_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
