# Generated by Django 2.1 on 2020-11-21 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0028_auto_20201121_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportuserevent',
            name='report_additional_info',
        ),
        migrations.RemoveField(
            model_name='reportuserevent',
            name='report_presence',
        ),
        migrations.RemoveField(
            model_name='reportuserevent',
            name='report_reason',
        ),
    ]
