# Generated by Django 2.1 on 2020-11-21 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0032_auto_20201121_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDataEvent',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('report_presence', models.BooleanField(default=False)),
                ('report_reason', models.CharField(blank=True, choices=[('sickness', 'Хворіє'), ('important', 'Поважна'), ('home', 'Home'), ('other', 'Other')], default=None, max_length=30, null=True, verbose_name='report_reason')),
                ('report_additional_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='report_info')),
                ('report_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='reportuserevent',
            name='report_user',
        ),
        migrations.AddField(
            model_name='reportuserevent',
            name='report_data_event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_data_event', to='nubip.ReportDataEvent'),
        ),
    ]
