# Generated by Django 2.1 on 2020-11-21 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0033_auto_20201121_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportuserevent',
            name='report_data_event',
        ),
    ]
