# Generated by Django 2.1 on 2020-11-21 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0036_auto_20201121_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='nubip.Event', verbose_name='Учасник'),
        ),
    ]
