# Generated by Django 2.1 on 2020-11-22 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0038_auto_20201122_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Кафери'},
        ),
        migrations.AlterModelOptions(
            name='membergroup',
            options={'verbose_name_plural': 'Члени групи'},
        ),
        migrations.AlterModelOptions(
            name='reportdataevent',
            options={'verbose_name_plural': 'Дані звітів'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'Профайли користувачів'},
        ),
        migrations.RemoveField(
            model_name='academicgroup',
            name='member',
        ),
        migrations.AlterField(
            model_name='academicgroup',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nubip.Department', verbose_name='Кафедра'),
        ),
    ]
