# Generated by Django 2.1 on 2020-11-22 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0039_auto_20201122_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department_head', to=settings.AUTH_USER_MODEL, verbose_name='Завідувач кафедри'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Назва кафедри'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('headman', 'Староста'), ('curator', 'Куратор'), ('teacher', 'Викладач'), ('head_department', 'Завідувач кафедри'), ('head_assistant', 'Заступник директора'), ('head', 'Директор'), ('admin', 'Admin')], max_length=20, verbose_name='role'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'head')},
        ),
    ]
