# Generated by Django 2.1 on 2020-11-22 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0040_auto_20201122_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicgroup',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nubip.Department', verbose_name='Базова каферда'),
        ),
        migrations.AlterField(
            model_name='academicgroup',
            name='name',
            field=models.CharField(default=None, max_length=25, verbose_name='Шифр групи'),
        ),
        migrations.AlterField(
            model_name='reportdataevent',
            name='report_additional_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Додаткова інформація'),
        ),
        migrations.AlterField(
            model_name='reportdataevent',
            name='report_reason',
            field=models.CharField(blank=True, choices=[('sickness', 'Хворіє'), ('important', 'Поважна'), ('home', 'Home'), ('other', 'Other')], default=None, max_length=30, null=True, verbose_name='Причина відсутності'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='additional_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Додаткова інформація'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='presence',
            field=models.BooleanField(default=False, verbose_name='Присутність'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='reason',
            field=models.CharField(blank=True, choices=[('sickness', 'Хворіє'), ('important', 'Поважна'), ('home', 'Home'), ('other', 'Other')], default=None, max_length=30, null=True, verbose_name='Причина відсутності'),
        ),
    ]
