# Generated by Django 2.1 on 2020-11-22 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0041_auto_20201122_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicgroup',
            name='curator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
        ),
    ]
