# Generated by Django 2.1 on 2020-11-28 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0042_academicgroup_curator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Номер по порядку')),
            ],
            options={
                'verbose_name_plural': 'Порядок занять',
            },
        ),
        migrations.CreateModel(
            name='LectureName',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Назва предмету')),
                ('member_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Викладач')),
            ],
            options={
                'verbose_name_plural': 'Предмет',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='index_number',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nubip.Lecture', verbose_name='Заняття за розкладом'),
        ),
        migrations.AddField(
            model_name='event',
            name='lecture',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nubip.LectureName', verbose_name='Назва предмету'),
        ),
        migrations.AlterUniqueTogether(
            name='lecturename',
            unique_together={('name', 'member_user')},
        ),
    ]
