# Generated by Django 2.1 on 2020-11-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0043_auto_20201128_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturename',
            old_name='member_user',
            new_name='teacher',
        ),
        migrations.AlterUniqueTogether(
            name='lecturename',
            unique_together={('name', 'teacher')},
        ),
    ]
