# Generated by Django 2.1 on 2021-01-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0044_auto_20201128_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'verbose_name_plural': 'Календар занять'},
        ),
        migrations.AlterModelOptions(
            name='lecturename',
            options={'verbose_name_plural': 'Перелік дисциплін'},
        ),
        migrations.AddField(
            model_name='academicgroup',
            name='course',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=None, max_length=32, null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(help_text='Рік місяць число', verbose_name='Дата проведення'),
        ),
    ]
