# Generated by Django 2.1 on 2021-01-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0045_auto_20210112_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Назва кафедри'),
        ),
    ]
