# Generated by Django 3.1.5 on 2021-01-17 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0046_auto_20210116_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportuserevent',
            name='report_creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_creator', to=settings.AUTH_USER_MODEL, verbose_name='Звіт створив'),
        ),
        migrations.AlterField(
            model_name='reportuserevent',
            name='report_event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_event', to='nubip.event', verbose_name='Дисципліна'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='reason',
            field=models.CharField(blank=True, choices=[('sickness', 'Хворіє'), ('important', 'Поважна'), ('home', 'Сімейні обставини'), ('other', 'Інше')], default=None, max_length=30, null=True, verbose_name='Причина відсутності'),
        ),
    ]
