# Generated by Django 3.1.5 on 2021-01-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0047_auto_20210117_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicgroup',
            name='name',
            field=models.CharField(default=None, max_length=500, verbose_name='Шифр групи'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Номер по порядку'),
        ),
        migrations.AlterField(
            model_name='lecturename',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Назва предмету'),
        ),
    ]
