# Generated by Django 3.1.5 on 2021-01-20 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0050_auto_20210120_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gev',
            name='gev_event',
        ),
        migrations.RemoveField(
            model_name='gev',
            name='index_number',
        ),
        migrations.RemoveField(
            model_name='gev',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='gev',
            name='notes',
        ),
        migrations.CreateModel(
            name='FGEV',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('gev_event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_user_gev', to='nubip.gev')),
                ('index_number', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nubip.lecture', verbose_name='Заняття за розкладом')),
                ('lecture', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nubip.lecturename', verbose_name='Назва предмету')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
