# Generated by Django 3.1.5 on 2021-01-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0051_auto_20210120_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(help_text='Місяць число рік', verbose_name='Дата проведення'),
        ),
    ]
