# Generated by Django 3.1.5 on 2021-02-02 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0052_auto_20210121_1548'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lecturename',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='TutorName',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lecture', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nubip.lecturename', verbose_name='Дисципліна')),
                ('teacher', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Викладач')),
            ],
            options={
                'verbose_name_plural': 'Викладач',
            },
        ),
        migrations.RemoveField(
            model_name='lecturename',
            name='teacher',
        ),
    ]
