# Generated by Django 3.1.5 on 2021-02-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0053_auto_20210202_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdataevent',
            name='protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reportdataevent',
            name='report_reason',
            field=models.CharField(blank=True, choices=[('sickness', 'Хворіє'), ('important', 'Поважна'), ('home', 'Сімейні обставини'), ('other', 'Інше')], default=None, max_length=30, null=True, verbose_name='Причина відсутності'),
        ),
    ]
