# Generated by Django 3.1.5 on 2021-02-09 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0054_auto_20210208_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='user_event_creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_event_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
