# Generated by Django 3.1.5 on 2021-02-09 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0055_userevent_user_event_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdataevent',
            name='user_event_creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_user_event_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
