# Generated by Django 3.1.5 on 2021-02-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0056_reportdataevent_user_event_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('day', models.DateField(help_text='Місяць число рік', verbose_name='Дата проведення')),
            ],
            options={
                'verbose_name_plural': 'Зведений Звіт',
            },
        ),
    ]
