# Generated by Django 3.1.5 on 2021-08-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0057_reportmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturename',
            options={'ordering': ['name'], 'verbose_name_plural': 'Перелік дисциплін'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name'], 'verbose_name_plural': 'Користувачі'},
        ),
        migrations.AddField(
            model_name='user',
            name='deducted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='deducted'),
        ),
        migrations.AddField(
            model_name='user',
            name='deducted_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='deducted_date'),
        ),
    ]
