# Generated by Django 3.1.5 on 2021-08-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0060_auto_20210826_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'verbose_name_plural': 'Порядок занять'},
        ),
        migrations.AddField(
            model_name='academicgroup',
            name='graduation',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='graduation'),
        ),
    ]
