# Generated by Django 3.1.5 on 2021-08-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0061_auto_20210826_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicgroup',
            options={'ordering': ['name'], 'verbose_name_plural': 'Академічні групи'},
        ),
    ]
