# Generated by Django 3.1.5 on 2021-09-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubip', '0062_auto_20210826_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdataevent',
            name='report_reason',
            field=models.CharField(blank=True, choices=[('sickness', 'Хворіє'), ('important', 'Поважна'), ('home', 'Сімейні обставини'), ('no_reason ', 'Безпричинно відсутній'), ('another_subgroup', 'Інша підгрупа'), ('other', 'Інше')], default=None, max_length=30, null=True, verbose_name='Причина відсутності'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='reason',
            field=models.CharField(blank=True, choices=[('sickness', 'Хворіє'), ('important', 'Поважна'), ('home', 'Сімейні обставини'), ('no_reason ', 'Безпричинно відсутній'), ('another_subgroup', 'Інша підгрупа'), ('individual_schedule', 'Індивідуальний графік'), ('other', 'Інше')], default=None, max_length=30, null=True, verbose_name='Причина відсутності'),
        ),
    ]
